####################################################################################################
# Author: Cuong. Duong Manh <cuongdm8499@gmail.com>
# Description:
#   - ServiceAccount for the vContainer-CCM
####################################################################################################

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}