{{ if .Values.vcontainerConfig.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.vcontainerConfig.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  vcontainer-config.conf: |-
    [Global]
    identity-url={{ printf "%s" .Values.vcontainerConfig.identityURL }}
    compute-url={{ printf "%s" .Values.vcontainerConfig.computeURL }}
    portal-url={{ printf "%s" .Values.vcontainerConfig.portalURL }}
    blockstorage-url={{ printf "%s" .Values.vcontainerConfig.blockstorageURL }}
    vbackup-gateway-url={{ printf "%s" .Values.vcontainerConfig.vBackUpGateWayURL }}
    client-id={{ printf "%s" .Values.vcontainerConfig.clientID }}
    client-secret={{ printf "%s" .Values.vcontainerConfig.clientSecret }}
    ca-file={{ printf "%s" .Values.vcontainerConfig.caFile }}
{{ end }}