####################################################################################################
# Author: Cuong. Duong Manh <cuongdm3@vng.com.vn>
# Description: 
#   - Deploy snapshot controller deployment, this deployment is needed to create, list, delete 
# snapshots.
#   - This deployment will be deployed in the same namespace with vcontainer-storage-interface.
####################################################################################################

apiVersion: v1
kind: ServiceAccount
metadata:
  name: vcontainer-csi-snapshot-controller-sa
  namespace: {{ .Release.Namespace }}
---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vcontainer-csi-snapshot-controller-cr
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotcontents"]
    verbs: ["create", "get", "list", "watch", "update", "delete"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots/status"]
    verbs: ["update"]
---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vcontainer-snapshot-controller-binding
subjects:
  - kind: ServiceAccount
    name: vcontainer-csi-snapshot-controller-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: vcontainer-csi-snapshot-controller-cr
  apiGroup: rbac.authorization.k8s.io
---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vcontainer-snapshot-controller-leaderelection-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "watch", "list", "delete", "update", "create"]
---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vcontainer-snapshot-controller-leaderelection-binding
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: vcontainer-csi-snapshot-controller-sa
roleRef:
  kind: Role
  name: vcontainer-snapshot-controller-leaderelection-role
  apiGroup: rbac.authorization.k8s.io
---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "vcontainer-storage-interface.name" . }}-snapshotcontroller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vcontainer-storage-interface.snapshot-controller.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: 2
  selector:
    matchLabels:
      {{- include "vcontainer-storage-interface.snapshot-controller.matchLabels" . | nindent 6 }}
  # the snapshot controller won't be marked as ready if the v1 CRDs are unavailable
  # in #504 the snapshot-controller will exit after around 7.5 seconds if it
  # can't find the v1 CRDs so this value should be greater than that
  minReadySeconds: 15
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "vcontainer-storage-interface.snapshot-controller.labels" . | nindent 8 }}
      annotations:
        {{- with .Values.commonAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccount: vcontainer-csi-snapshot-controller-sa
      containers:
        - name: vcontainer-snapshot-controller
          image: "{{ .Values.csi.snapshotController.image.repository }}:{{ .Values.csi.snapshotController.image.tag }}"
          args:
            - "--v=5"
            - "--leader-election=true"
            {{- if .Values.csi.snapshotController.extraArgs }}
            {{- with .Values.csi.snapshotController.extraArgs }}
            {{- tpl . $ | trim | nindent 12 }}
            {{- end }}
            {{- end }}
          imagePullPolicy: IfNotPresent
