{{- if .Values.storageClass.enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: vcontainer-storage-interface-delete
  {{- if .Values.storageClass.delete.isDefault }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  {{- end }}
provisioner: csi.vngcloud.vn
reclaimPolicy: Delete
parameters:
  type: vtype-6d30737c-08aa-41f8-8bb1-d486c94ccf69
allowVolumeExpansion: {{ .Values.storageClass.delete.allowVolumeExpansion }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: vcontainer-storage-interface-retain
  {{- if .Values.storageClass.retain.isDefault }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  {{- end }}
provisioner: csi.vngcloud.vn
reclaimPolicy: Retain
parameters:
  type: vtype-6d30737c-08aa-41f8-8bb1-d486c94ccf69
allowVolumeExpansion: {{ .Values.storageClass.retain.allowVolumeExpansion }}
{{- end }}